// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAJVL4ly9Z_E_atjrt5ATnPyW2ZvTdfik',
    appId: '1:449655927468:web:3d607412a7af9e35f72509',
    messagingSenderId: '449655927468',
    projectId: 'gleamhomeai',
    authDomain: 'gleamhomeai.firebaseapp.com',
    storageBucket: 'gleamhomeai.firebasestorage.app',
    measurementId: 'G-MYP83ZPP2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCMUZzGNcRzPSIydcLivD51YHfeov-Ee0',
    appId: '1:449655927468:android:c4cfe3402fdab3a7f72509',
    messagingSenderId: '449655927468',
    projectId: 'gleamhomeai',
    storageBucket: 'gleamhomeai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJegv4Cp4XGYs6KUBn6u36SYo3VuOz4a4',
    appId: '1:449655927468:ios:385d890d047c9ad9f72509',
    messagingSenderId: '449655927468',
    projectId: 'gleamhomeai',
    storageBucket: 'gleamhomeai.firebasestorage.app',
    iosClientId: '449655927468-bnqjbrlj0s7ol49j7d135b72sqptg8eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gleamhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJegv4Cp4XGYs6KUBn6u36SYo3VuOz4a4',
    appId: '1:449655927468:ios:385d890d047c9ad9f72509',
    messagingSenderId: '449655927468',
    projectId: 'gleamhomeai',
    storageBucket: 'gleamhomeai.firebasestorage.app',
    iosClientId: '449655927468-bnqjbrlj0s7ol49j7d135b72sqptg8eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gleamhome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAJVL4ly9Z_E_atjrt5ATnPyW2ZvTdfik',
    appId: '1:449655927468:web:9fc54440d52352fcf72509',
    messagingSenderId: '449655927468',
    projectId: 'gleamhomeai',
    authDomain: 'gleamhomeai.firebaseapp.com',
    storageBucket: 'gleamhomeai.firebasestorage.app',
    measurementId: 'G-JXQJS72WL5',
  );
}
